global_frame: odom
# static_map: false
rolling_window: true
track_unknown_space: true
width: 2.2
height: 2.2
resolution: 0.05
origin_x: -3.0
origin_y: -2.8

plugins:
  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}