footprint: [[-0.05, -0.02], [-0.05, 0.08], [0.05, 0.08], [0.05, -0.02]]
footprint_padding: 0.05 #0.01

robot_base_frame: base_footprint
update_frequency: 4.0 #2.0
publish_frequency: 3.0 #1.5 #3.0
transform_tolerance: 0.5

resolution: 0.01 #0.1

obstacle_range: 2.0
raytrace_range: 20.0 

#layer definitions
static_layer:
    map_topic: /map
    subscribe_to_updates: false
    lethal_cost_threshold: 100
    track_unknown_space: true
    use_maximum: false
    trinary_costmap: true

obstacles_layer:
    observation_sources: scan
    scan: {sensor_frame: lds_frame_gazebo, 
    data_type: LaserScan, 
    clearing: true, 
    marking: true, 
    topic: /bbot/laser/scan,
    observation_persistence: 0.0,
    inf_is_valid: true}   

inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 3 #TODO testar diminuir